/* ========== ĐỘNG TỪ BẤT QUY TẮC ========== */
const IRREGULAR_VERBS = [
  /* ===== LEVEL 1: CƠ BẢN (50 từ) ===== */
  { level:1, v1:'be', v2:'was/were', v3:'been', vi:'thì, là, ở', ex:'I have been to Japan.' },
  { level:1, v1:'have', v2:'had', v3:'had', vi:'có', ex:'She has had lunch.' },
  { level:1, v1:'do', v2:'did', v3:'done', vi:'làm', ex:'I have done my homework.' },
  { level:1, v1:'go', v2:'went', v3:'gone', vi:'đi', ex:'He has gone to school.' },
  { level:1, v1:'get', v2:'got', v3:'got/gotten', vi:'nhận, lấy', ex:'I have got a new phone.' },
  { level:1, v1:'make', v2:'made', v3:'made', vi:'làm, tạo', ex:'She has made a cake.' },
  { level:1, v1:'take', v2:'took', v3:'taken', vi:'lấy, cầm', ex:'I have taken the bus.' },
  { level:1, v1:'come', v2:'came', v3:'come', vi:'đến', ex:'They have come home.' },
  { level:1, v1:'see', v2:'saw', v3:'seen', vi:'thấy', ex:'I have seen that movie.' },
  { level:1, v1:'know', v2:'knew', v3:'known', vi:'biết', ex:'I have known her for years.' },
  { level:1, v1:'give', v2:'gave', v3:'given', vi:'cho', ex:'He has given me a gift.' },
  { level:1, v1:'find', v2:'found', v3:'found', vi:'tìm thấy', ex:'I have found my keys.' },
  { level:1, v1:'think', v2:'thought', v3:'thought', vi:'nghĩ', ex:'I have thought about it.' },
  { level:1, v1:'tell', v2:'told', v3:'told', vi:'kể, nói', ex:'She has told me the truth.' },
  { level:1, v1:'become', v2:'became', v3:'become', vi:'trở thành', ex:'He has become a doctor.' },
  { level:1, v1:'leave', v2:'left', v3:'left', vi:'rời đi', ex:'They have left already.' },
  { level:1, v1:'feel', v2:'felt', v3:'felt', vi:'cảm thấy', ex:'I have felt tired lately.' },
  { level:1, v1:'put', v2:'put', v3:'put', vi:'đặt, để', ex:'I have put it on the table.' },
  { level:1, v1:'bring', v2:'brought', v3:'brought', vi:'mang đến', ex:'She has brought her friend.' },
  { level:1, v1:'begin', v2:'began', v3:'begun', vi:'bắt đầu', ex:'The movie has begun.' },
  { level:1, v1:'keep', v2:'kept', v3:'kept', vi:'giữ', ex:'I have kept my promise.' },
  { level:1, v1:'hold', v2:'held', v3:'held', vi:'giữ, cầm', ex:'He has held my hand.' },
  { level:1, v1:'write', v2:'wrote', v3:'written', vi:'viết', ex:'I have written a letter.' },
  { level:1, v1:'stand', v2:'stood', v3:'stood', vi:'đứng', ex:'We have stood here for hours.' },
  { level:1, v1:'hear', v2:'heard', v3:'heard', vi:'nghe', ex:'I have heard that song.' },
  { level:1, v1:'let', v2:'let', v3:'let', vi:'để cho', ex:'She has let me go.' },
  { level:1, v1:'mean', v2:'meant', v3:'meant', vi:'có nghĩa', ex:'What have you meant?' },
  { level:1, v1:'set', v2:'set', v3:'set', vi:'đặt, lập', ex:'I have set the alarm.' },
  { level:1, v1:'meet', v2:'met', v3:'met', vi:'gặp', ex:'I have met him before.' },
  { level:1, v1:'run', v2:'ran', v3:'run', vi:'chạy', ex:'He has run 5 kilometers.' },
  { level:1, v1:'pay', v2:'paid', v3:'paid', vi:'trả tiền', ex:'I have paid the bill.' },
  { level:1, v1:'sit', v2:'sat', v3:'sat', vi:'ngồi', ex:'She has sat here all day.' },
  { level:1, v1:'speak', v2:'spoke', v3:'spoken', vi:'nói', ex:'I have spoken to him.' },
  { level:1, v1:'lie', v2:'lay', v3:'lain', vi:'nằm', ex:'He has lain on the bed.' },
  { level:1, v1:'lead', v2:'led', v3:'led', vi:'dẫn dắt', ex:'She has led the team.' },
  { level:1, v1:'read', v2:'read', v3:'read', vi:'đọc', ex:'I have read that book.' },
  { level:1, v1:'grow', v2:'grew', v3:'grown', vi:'mọc, phát triển', ex:'The tree has grown tall.' },
  { level:1, v1:'lose', v2:'lost', v3:'lost', vi:'mất', ex:'I have lost my wallet.' },
  { level:1, v1:'fall', v2:'fell', v3:'fallen', vi:'rơi, ngã', ex:'The leaves have fallen.' },
  { level:1, v1:'send', v2:'sent', v3:'sent', vi:'gửi', ex:'I have sent the email.' },
  { level:1, v1:'build', v2:'built', v3:'built', vi:'xây', ex:'They have built a house.' },
  { level:1, v1:'understand', v2:'understood', v3:'understood', vi:'hiểu', ex:'I have understood the lesson.' },
  { level:1, v1:'draw', v2:'drew', v3:'drawn', vi:'vẽ', ex:'She has drawn a picture.' },
  { level:1, v1:'break', v2:'broke', v3:'broken', vi:'làm vỡ', ex:'He has broken the vase.' },
  { level:1, v1:'spend', v2:'spent', v3:'spent', vi:'tiêu, dành', ex:'I have spent 100 dollars.' },
  { level:1, v1:'cut', v2:'cut', v3:'cut', vi:'cắt', ex:'She has cut her hair.' },
  { level:1, v1:'rise', v2:'rose', v3:'risen', vi:'tăng, mọc', ex:'The sun has risen.' },
  { level:1, v1:'drive', v2:'drove', v3:'driven', vi:'lái xe', ex:'I have driven for 5 years.' },
  { level:1, v1:'buy', v2:'bought', v3:'bought', vi:'mua', ex:'I have bought a new car.' },
  { level:1, v1:'wear', v2:'wore', v3:'worn', vi:'mặc', ex:'She has worn that dress.' },

  /* ===== LEVEL 2: TRUNG BÌNH (30 từ) ===== */
  { level:2, v1:'choose', v2:'chose', v3:'chosen', vi:'chọn', ex:'I have chosen the red one.' },
  { level:2, v1:'catch', v2:'caught', v3:'caught', vi:'bắt', ex:'He has caught the ball.' },
  { level:2, v1:'fight', v2:'fought', v3:'fought', vi:'chiến đấu', ex:'They have fought bravely.' },
  { level:2, v1:'teach', v2:'taught', v3:'taught', vi:'dạy', ex:'She has taught for 10 years.' },
  { level:2, v1:'forget', v2:'forgot', v3:'forgotten', vi:'quên', ex:'I have forgotten his name.' },
  { level:2, v1:'freeze', v2:'froze', v3:'frozen', vi:'đông lạnh', ex:'The water has frozen.' },
  { level:2, v1:'hide', v2:'hid', v3:'hidden', vi:'giấu', ex:'He has hidden the money.' },
  { level:2, v1:'hit', v2:'hit', v3:'hit', vi:'đánh', ex:'She has hit the ball.' },
  { level:2, v1:'hurt', v2:'hurt', v3:'hurt', vi:'làm đau', ex:'I have hurt my leg.' },
  { level:2, v1:'lie', v2:'lied', v3:'lied', vi:'nói dối', ex:'He has lied to me.' },
  { level:2, v1:'ride', v2:'rode', v3:'ridden', vi:'cưỡi, đi', ex:'I have ridden a horse.' },
  { level:2, v1:'ring', v2:'rang', v3:'rung', vi:'reo', ex:'The phone has rung.' },
  { level:2, v1:'sell', v2:'sold', v3:'sold', vi:'bán', ex:'They have sold the house.' },
  { level:2, v1:'shake', v2:'shook', v3:'shaken', vi:'lắc', ex:'He has shaken my hand.' },
  { level:2, v1:'shine', v2:'shone', v3:'shone', vi:'chiếu sáng', ex:'The sun has shone brightly.' },
  { level:2, v1:'shoot', v2:'shot', v3:'shot', vi:'bắn', ex:'He has shot the target.' },
  { level:2, v1:'show', v2:'showed', v3:'shown', vi:'cho xem', ex:'She has shown me the way.' },
  { level:2, v1:'shut', v2:'shut', v3:'shut', vi:'đóng', ex:'I have shut the door.' },
  { level:2, v1:'sing', v2:'sang', v3:'sung', vi:'hát', ex:'She has sung beautifully.' },
  { level:2, v1:'sink', v2:'sank', v3:'sunk', vi:'chìm', ex:'The ship has sunk.' },
  { level:2, v1:'sleep', v2:'slept', v3:'slept', vi:'ngủ', ex:'I have slept for 8 hours.' },
  { level:2, v1:'smell', v2:'smelt', v3:'smelt', vi:'ngửi', ex:'I have smelt the flowers.' },
  { level:2, v1:'steal', v2:'stole', v3:'stolen', vi:'ăn cắp', ex:'Someone has stolen my bike.' },
  { level:2, v1:'swim', v2:'swam', v3:'swum', vi:'bơi', ex:'I have swum in the sea.' },
  { level:2, v1:'swear', v2:'swore', v3:'sworn', vi:'thề', ex:'He has sworn to help.' },
  { level:2, v1:'sweep', v2:'swept', v3:'swept', vi:'quét', ex:'She has swept the floor.' },
  { level:2, v1:'throw', v2:'threw', v3:'thrown', vi:'ném', ex:'He has thrown the ball.' },
  { level:2, v1:'wake', v2:'woke', v3:'woken', vi:'thức dậy', ex:'I have woken up early.' },
  { level:2, v1:'win', v2:'won', v3:'won', vi:'thắng', ex:'They have won the game.' },
  { level:2, v1:'feed', v2:'fed', v3:'fed', vi:'cho ăn', ex:'I have fed the cat.' },

  /* ===== LEVEL 3: NÂNG CAO (20 từ) ===== */
  { level:3, v1:'arise', v2:'arose', v3:'arisen', vi:'nảy sinh', ex:'A problem has arisen.' },
  { level:3, v1:'awake', v2:'awoke', v3:'awoken', vi:'thức giấc', ex:'I have awoken at dawn.' },
  { level:3, v1:'bear', v2:'bore', v3:'borne', vi:'chịu đựng', ex:'She has borne the pain.' },
  { level:3, v1:'beat', v2:'beat', v3:'beaten', vi:'đánh bại', ex:'They have beaten the champion.' },
  { level:3, v1:'bend', v2:'bent', v3:'bent', vi:'bẻ cong', ex:'He has bent the metal.' },
  { level:3, v1:'bet', v2:'bet', v3:'bet', vi:'cá cược', ex:'I have bet on that horse.' },
  { level:3, v1:'bind', v2:'bound', v3:'bound', vi:'buộc', ex:'They have bound his hands.' },
  { level:3, v1:'bite', v2:'bit', v3:'bitten', vi:'cắn', ex:'The dog has bitten him.' },
  { level:3, v1:'bleed', v2:'bled', v3:'bled', vi:'chảy máu', ex:'My nose has bled.' },
  { level:3, v1:'blow', v2:'blew', v3:'blown', vi:'thổi', ex:'The wind has blown hard.' },
  { level:3, v1:'breed', v2:'bred', v3:'bred', vi:'nuôi, gây giống', ex:'They have bred horses.' },
  { level:3, v1:'cast', v2:'cast', v3:'cast', vi:'đúc, ném', ex:'He has cast the spell.' },
  { level:3, v1:'cling', v2:'clung', v3:'clung', vi:'bám chặt', ex:'She has clung to hope.' },
  { level:3, v1:'creep', v2:'crept', v3:'crept', vi:'bò', ex:'The cat has crept inside.' },
  { level:3, v1:'deal', v2:'dealt', v3:'dealt', vi:'giải quyết', ex:'I have dealt with it.' },
  { level:3, v1:'dig', v2:'dug', v3:'dug', vi:'đào', ex:'They have dug a hole.' },
  { level:3, v1:'flee', v2:'fled', v3:'fled', vi:'chạy trốn', ex:'The thief has fled.' },
  { level:3, v1:'forbid', v2:'forbade', v3:'forbidden', vi:'cấm', ex:'Smoking has been forbidden.' },
  { level:3, v1:'forgive', v2:'forgave', v3:'forgiven', vi:'tha thứ', ex:'I have forgiven him.' },
  { level:3, v1:'hang', v2:'hung', v3:'hung', vi:'treo', ex:'She has hung the picture.' }
];
